---
- name: Deploy Calculator Application
  hosts: all

  vars:
    ansible_python_interpreter: /Users/vikaskaly/base/bin/python

  tasks:
  
    - name: Pull Image
      shell: docker pull vikaskaly/spe-miniproject-calculator:latest

    - name: Run the container
      shell: docker create -it --name Calculator vikaskaly/spe-miniproject-calculator
